package router

import (
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"net/http"
	_ "projeto-magalu-api-go/docs" // docs is generated by Swag CLI, you have to import it.
	"projeto-magalu-api-go/pkg/api/controller"
)

// NewRARouter creates a new router with all the necessary routes
func NewRARouter(
	transactionController controller.TransactionCtrl,
	pulseController controller.PulseCtrl,
	healthController *controller.HealthHandler,
	tenantController controller.TenantCtrl,
	productController controller.ProductCtrl,
	contractController controller.ContractCtrl,
) http.Handler {
	router := mux.NewRouter()
	router.HandleFunc("/", handleHome)
	router.HandleFunc("/pulses", pulseController.CreatePulse).Methods("POST")
	router.HandleFunc("/transactions", transactionController.CreateTransaction).Methods("POST")
	router.HandleFunc("/payment", transactionController.BalancePayment).Methods("POST")
	router.HandleFunc("/health", healthController.Healthcheck).Methods("GET")

	// New routes for querying consumption
	router.HandleFunc("/tenants/{tenant}/sku/{sku}/consumption", pulseController.GetCurrentMonthConsumption).Methods("GET")
	router.HandleFunc("/tenants/{tenant}/consumption", pulseController.GetAllResourcesConsumption).Methods("GET")

	// New Routes for Tenants, Products, and Contracts
	router.HandleFunc("/tenants", tenantController.CreateTenant).Methods("POST")
	router.HandleFunc("/tenants/{id}", tenantController.GetTenant).Methods("GET")
	router.HandleFunc("/products", productController.CreateProduct).Methods("POST")
	router.HandleFunc("/products/{id}", productController.GetProduct).Methods("GET")
	router.HandleFunc("/contracts", contractController.CreateContract).Methods("POST")
	router.HandleFunc("/contracts/{id}", contractController.GetContract).Methods("GET")

	// Swagger
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	return router
}

func handleHome(w http.ResponseWriter, r *http.Request) {
	msg := []byte("Welcome to Thiago API")
	w.Write(msg)
}
