// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	"go.mongodb.org/mongo-driver/bson/primitive"
	model "projeto-magalu-api-go/pkg/api/model"
)

type MockTransactionRepository struct{}

func (m *MockTransactionRepository) BalancePayment(ctx context.Context, transaction *model.Transaction) (*model.Transaction, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockTransactionRepository) Create(ctx context.Context, transaction *model.Transaction) (*model.Transaction, error) {
	return &model.Transaction{
		ID:        primitive.NewObjectID(),
		TenantID: transaction.TenantID,
		Amount:    transaction.Amount,
	}, nil
}